# .pre-commit-config.yaml

repos:
-   repo: local
    hooks:
    -   id: regression-tests
        name: Run Options-Zero-Game Regression Suite
        # We use 'bash -c' to create a shell, set the PYTHONPATH for that
        # shell's environment, and then execute our script.
        entry: bash -c 'PYTHONPATH=. python3 zoo/options_zero_game/entry/regression_suite.py'
        language: system
        pass_filenames: false
        stages: [commit]
