# .github/workflows/ci.yml

name: Regression Test Suite

# This section is now correctly configured for YOUR branch.
on:
  # Run on every push to the options_zero_game branch
  push:
    branches: [ "options_zero_game" ]
  # Run on every pull request that targets the options_zero_game branch
  pull_request:
    branches: [ "options_zero_game" ]

jobs:
  run-regression-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming requirements.txt is at the root of your repo
          pip install -r requirements.txt

      # Step 5: Run the regression test suite with the correct Python path.
      - name: Run regression test suite
        run: |
          PYTHONPATH=. python3 zoo/options_zero_game/entry/regression_suite.py
